### ISSUE TITLE
CLI: runtime error when using –volume parameter

### ISSUE THREAD

**Issue by nitram509** [drone/drone-cli#113]
See also:
https://discourse.drone.io/t/cli-runtime-error-when-using-volume-parameter/3327

Context:

using drone cli 1.0.4
having a local .drone.yml
running command ```drone exec --volume /tmp/xxx``` (it doesn’t matter if the folder exists or not)
A runtime error happens.

Expected behavior: no runtime error, but a proper error message that would guide me how to solve the problem.

```
drone exec --volume /tmp/xxx
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/drone/drone-cli/drone/exec.toVolumes(0xc4203b05c0, 0x1, 0x1, 0x6)
	/go/src/github.com/drone/drone-cli/drone/exec/exec.go:316 +0x16c
github.com/drone/drone-cli/drone/exec.exec(0xc4200834a0, 0x0, 0x0)
	/go/src/github.com/drone/drone-cli/drone/exec/exec.go:262 +0xbd5
github.com/drone/drone-cli/drone/exec.glob..func1(0xc4200834a0)
	/go/src/github.com/drone/drone-cli/drone/exec/exec.go:40 +0x2b
github.com/drone/drone-cli/vendor/github.com/urfave/cli.HandleAction(0x14cea40, 0x15c6680, 0xc4200834a0, 0xc42023b300, 0x0)
	/go/src/github.com/drone/drone-cli/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/drone/drone-cli/vendor/github.com/urfave/cli.Command.Run(0x15957d0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15a1d48, 0x15, 0x0, ...)
	/go/src/github.com/drone/drone-cli/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/drone/drone-cli/vendor/github.com/urfave/cli.(*App).Run(0xc420072b60, 0xc42000e100, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/drone/drone-cli/vendor/github.com/urfave/cli/app.go:255 +0x6f8
main.main()
	/go/src/github.com/drone/drone-cli/drone/main.go:98 +0xa30
```

PS: I plan to prepare a patch, but found it useful to create an issue first.

**Comment by nitram509** [comment]
I did confirm with v1.0.5 release, this was fixed.

The issue can be closed.

Thank you, everyone, for your support in fixing this.
